---
# dnf install policycoreutils-python-utils -y
- name: Install policycoreutils-python-utils
  ansible.builtin.dnf:
    name:
      - policycoreutils-python-utils
    state: present

# semanage port -l | grep http_port_t
# http_port_t                    tcp      443, 488, 8008, 8009, 8443, 9000

# semanage port -a -t http_port_t -p tcp 80

# semanage port -l | grep http_port_t
# http_port_t                    tcp      80, 443, 488, 8008, 8009, 8443, 9000

# sudo semanage fcontext -a -t samba_share_t "/data(/.*)?"
# sudo restorecon -R /data

## semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html(/.*)?"
#- name: Allow apache to modify files in /srv/git_repos
#  community.general.sefcontext:
#    target: '/var/www/html(/.*)?'
#    setype: httpd_sys_rw_content_t
#    state: present

# setsebool -P httpd_can_network_relay 1
- name: Set httpd_can_network_relay flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_relay
    - nis_enabled
